[project]
name = "obfuscation"

[topo]
root = "topo/main.topo"

[build]
sources = ["src/*.cpp"]
include = ["include"]
standard = "c++17"
output = "obfuscation_base"

[builder]
mode = "dev"
obfuscation = "normal"
