[project]
name = "loop_parallel"

[topo]
root = "topo/main.topo"

[build]
sources = ["src/*.cpp"]
include = ["include", "../../../topo-lang-cpp/runtime/include", "../../runtime/include"]
standard = "c++17"
output = "loop_parallel_base"

[parallel]
mode = "off"
min_tasks_to_parallelize = 2

[loop_parallel]
mode = "off"
