#ifndef TOPO_ADAPTIVE_RT_H
#define TOPO_ADAPTIVE_RT_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/// ABI version — bump when any signature in this header changes (add/remove
/// parameter, change parameter or return type, change calling convention).
/// Adding a NEW entry point without touching existing ones is backward
/// compatible and does NOT require a bump.
///
/// Consumers obtain the runtime's actual version via topo_adaptive_version()
/// at process start and compare against TOPO_ADAPTIVE_ABI_VERSION; mismatch
/// is a hard error. See topo-llvm/runtime/ABI-COMPAT.md for the compatibility
/// matrix and bump history.
///
/// v1: initial pinned baseline (register, init, shutdown).
#define TOPO_ADAPTIVE_ABI_VERSION 1

/// Report the runtime's compiled-in TOPO_ADAPTIVE_ABI_VERSION. Consumers
/// (typically a one-time ctor injected by AdaptiveDispatchPass) call this
/// and abort on mismatch with their own TOPO_ADAPTIVE_ABI_VERSION.
uint32_t topo_adaptive_version(void);

/// Register a pipeline for adaptive monitoring.
/// Called from global constructors generated by AdaptiveDispatchPass.
///
/// @param mangled_name   Mangled function name (for JIT lookup)
/// @param pipeline_name  Pipeline qualified name (for cost sample lookup)
/// @param jit_ptr        Pointer to the __jit_ptr global variable
/// @param aot_tti_cost   Compile-time TTI cost estimate
void topo_adaptive_register(const char* mangled_name, const char* pipeline_name, void** jit_ptr, uint64_t aot_tti_cost);

/// Initialize the adaptive monitoring thread.
void topo_adaptive_init(void);

/// Shut down the adaptive monitoring thread.
void topo_adaptive_shutdown(void);

#ifdef __cplusplus
}
#endif

#endif // TOPO_ADAPTIVE_RT_H
