# Plan 28 Phase 4 — per-case category label injection.
#
# Usage:
#   topo_inject_bench_category_labels(<source>)
#
# <source> is the benchmark test translation unit (`PassBenchmarkTests.cpp`
# or `JvmBenchmarkTests.cpp`). This function:
#   1. parses `CATEGORY_BENCH_TEST_F(<Cat>, <Suite>, <Name>)` invocations
#   2. synthesises the discovered gtest test name `<Suite>_<Cat>_<Name>.Run`
#   3. emits a CMake fragment that appends a lowercase `<cat>` label to
#      each test
#   4. registers the fragment as a directory `TEST_INCLUDE_FILES` entry so
#      ctest loads it after gtest_discover_tests's own include stanza
#
# Runs at configure time; no dependency on CMake directory TESTS property
# (which is unavailable in ctest script mode).

function(topo_inject_bench_category_labels source_file)
    file(STRINGS "${source_file}" _topo_bench_lines
         REGEX "CATEGORY_BENCH_TEST_F\\([A-Za-z]+,[ \t]*[A-Za-z_][A-Za-z0-9_]*,[ \t]*[A-Za-z_][A-Za-z0-9_]*\\)")

    set(_topo_bench_entries "")
    foreach(_line IN LISTS _topo_bench_lines)
        # Parse `CATEGORY_BENCH_TEST_F(CAT, Suite, Name)` — tolerate whitespace.
        if(_line MATCHES "CATEGORY_BENCH_TEST_F\\(([A-Za-z]+),[ \t]*([A-Za-z_][A-Za-z0-9_]*),[ \t]*([A-Za-z_][A-Za-z0-9_]*)\\)")
            set(_cat "${CMAKE_MATCH_1}")
            set(_suite "${CMAKE_MATCH_2}")
            set(_name "${CMAKE_MATCH_3}")
            string(TOLOWER "${_cat}" _cat_lower)
            # Guard: reject categories not in the authoritative set (defence
            # against a typo landing silently).
            if(NOT _cat_lower MATCHES "^(opt|enhance|covered|instrument|runtime|infra)$")
                message(WARNING
                    "topo_inject_bench_category_labels: unknown category '${_cat}' in ${source_file}")
                continue()
            endif()
            set(_test_name "${_suite}_${_cat}_${_name}.Run")
            # Use `set_tests_properties(... PROPERTIES LABELS ...)` because
            # CTest's own interpreter for CTestTestfile.cmake supports it
            # natively, whereas `set_property(TEST)` is not available in
            # that context. We must *also* re-emit the base labels from
            # gtest_discover_tests because CTest's set_tests_properties
            # LABELS replaces rather than appends here.
            list(APPEND _topo_bench_entries
                 "set_tests_properties([=[${_test_name}]=] PROPERTIES LABELS [=[e2e;perf;benchmark;${_cat_lower}]=])")
        endif()
    endforeach()

    if(NOT _topo_bench_entries)
        return()
    endif()

    # Dedup — the LLVM file uses a preprocessor macro
    # (TOPO_CLASS_TEMPLATE_MICRO) that expands to multiple CATEGORY_BENCH_TEST_F
    # invocations. We only see the macro DEFINITION in the source regex, not
    # the expansions, so there's nothing to dedup from the ClassTemplate
    # micros here — but keep the dedup step as a safety net.
    list(REMOVE_DUPLICATES _topo_bench_entries)

    # Emit to a per-source fragment under the build dir so LLVM/JVM have
    # independent files.
    get_filename_component(_src_name "${source_file}" NAME_WE)
    set(_out "${CMAKE_CURRENT_BINARY_DIR}/${_src_name}_category_labels.cmake")
    set(_body "# Generated by topo_inject_bench_category_labels — do not edit\n")
    foreach(_e IN LISTS _topo_bench_entries)
        string(APPEND _body "${_e}\n")
    endforeach()
    file(WRITE "${_out}" "${_body}")

    # Register the fragment so CTest includes it after gtest_discover_tests.
    set_property(DIRECTORY APPEND PROPERTY TEST_INCLUDE_FILES "${_out}")
endfunction()

# Helper for the macro-driven ClassTemplate micro-benchmarks — they do not
# appear in the grep above (the macro body hides inside
# `TOPO_CLASS_TEMPLATE_MICRO`). Pass the expanded list explicitly.
function(topo_inject_bench_category_labels_explicit category suite names_var)
    string(TOLOWER "${category}" _cat_lower)
    set(_body "# Generated by topo_inject_bench_category_labels_explicit (${category}) — do not edit\n")
    foreach(_name IN LISTS ${names_var})
        set(_test_name "${suite}_${category}_${_name}.Run")
        string(APPEND _body
            "set_tests_properties([=[${_test_name}]=] PROPERTIES LABELS [=[e2e;perf;benchmark;${_cat_lower}]=])\n")
    endforeach()

    string(MAKE_C_IDENTIFIER "${suite}_${category}_extra" _key)
    set(_out "${CMAKE_CURRENT_BINARY_DIR}/${_key}_category_labels.cmake")
    file(WRITE "${_out}" "${_body}")
    set_property(DIRECTORY APPEND PROPERTY TEST_INCLUDE_FILES "${_out}")
endfunction()
