# Convert a binary file into a C++ header declaring a constexpr byte
# array.  Invoked at build time from test_pipeline_bitcode.cmake via
# cmake -P to stay cross-platform (no xxd / bin2c dependency).

if(NOT DEFINED INPUT_FILE OR NOT DEFINED OUTPUT_FILE OR NOT DEFINED ARRAY_NAME)
    message(FATAL_ERROR "INPUT_FILE, OUTPUT_FILE, and ARRAY_NAME must be defined.")
endif()

file(READ "${INPUT_FILE}" _HEX HEX)
string(LENGTH "${_HEX}" _HEX_LEN)
math(EXPR _BYTE_COUNT "${_HEX_LEN} / 2")

set(_BODY "")
set(_COL 0)
set(_I 0)
while(_I LESS _HEX_LEN)
    string(SUBSTRING "${_HEX}" ${_I} 2 _PAIR)
    if(_COL EQUAL 0)
        string(APPEND _BODY "    ")
    endif()
    string(APPEND _BODY "0x${_PAIR},")
    math(EXPR _COL "${_COL} + 1")
    if(_COL EQUAL 16)
        string(APPEND _BODY "\n")
        set(_COL 0)
    else()
        string(APPEND _BODY " ")
    endif()
    math(EXPR _I "${_I} + 2")
endwhile()
if(NOT _COL EQUAL 0)
    string(APPEND _BODY "\n")
endif()

set(_CONTENT
"// Auto-generated by embed_bitcode.cmake — do not edit.\n"
"#pragma once\n"
"\n"
"#include <cstddef>\n"
"#include <cstdint>\n"
"\n"
"inline constexpr unsigned char ${ARRAY_NAME}[] = {\n"
"${_BODY}"
"}\;\n"
"\n"
"inline constexpr std::size_t ${ARRAY_NAME}Size = ${_BYTE_COUNT}\;\n"
)

file(WRITE "${OUTPUT_FILE}" ${_CONTENT})
